WITH P AS (
  SELECT
    ID,
    PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC, ID) AS r
  FROM ECOLI_DATA
)
SELECT
  ID,
  CASE
    WHEN r <= 0.25 THEN 'CRITICAL'
    WHEN r <= 0.50 THEN 'HIGH'
    WHEN r <= 0.75 THEN 'MEDIUM'
    ELSE 'LOW'
  END AS COLONY_NAME
FROM P
ORDER BY ID;
